
server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SUPPORT_EMAIL}
#    password: ${APP_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  docker:
    compose:
      enabled: false

  profiles:
    active: dev

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-time: 120000 # 2 minutes (in milliseconds) (900000 for 15 minutes)
    refresh-token-expiration-time: 604800000 # 7 days (in milliseconds)

mechanics:
  service:
    url: http://mechanics:8082

spring.config.import: optional:file:.env[.properties]

